### ISSUE TITLE
Using binary ratings to estimate AUC - is it okay?

### ISSUE THREAD

**Issue by technOslerphile** [DIDSR/mitoticFigureCounts#1]
This paper estimates AUC of readers by averaging sensitivity and specificity because only binary ratings were available from the readers. So in the ROC curve, there is only a single point. 
Is this method acceptable in MRMC studies?

**Comment by brandon-gallas** [comment]
I don't know what paper you are referring to, but the only cautions I would have are related to the binary ratings. Please refer to this paper:
- F. Samuelson et al., “The Importance of ROC Data,” _Acad Radiol_, **vol. 18**, no. 2, pp. 257–258, Feb. 2011, doi: [10.1016/j.acra.2010.10.016](https://doi.org/10.1016/j.acra.2010.10.016).

**Comment by technOslerphile** [comment]
> I don't know what paper you are referring to, but the only cautions I would have are related to the binary ratings. Please refer to this paper:
> 
> * F. Samuelson et al., “The Importance of ROC Data,” _Acad Radiol_, **vol. 18**, no. 2, pp. 257–258, Feb. 2011, doi: [10.1016/j.acra.2010.10.016](https://doi.org/10.1016/j.acra.2010.10.016).

I meant the paper for mitoticFigureCounts itself.
`Tabata, K., N. Uraoka, J. Benhamida, M. G. Hanna, S. J. Sirintrapun, B. D. Gallas, Q. Gong, R. G. Aly, K. Emoto, K. M. Matsuda, M. R. Hameed, D. S. Klimstra, and Y. Yagi (2019). "Validation of mitotic cell quantification via microscopy and multiple whole-slide scanners." Diagn Pathol, 14(1): 65.`

Average of sensitivity and specificity is taken as AUC as confidence ratings from pathologist readers were not available, only binary ratings were available. Would this approach be okay ? Typically we estimate AUC of readers only when confidence ratings from readers are available where we can compute sensitivity and specificity at multiple threshold points. In case of binary ratings from readers, there is only a single threshold point.

**Comment by brandon-gallas** [comment]
The approach is ok with the warning that reader behavior often depends on prevalence, as discussed in the paper, "The Importance of ROC Data." The generalizability of binary performance data from humans is always suspect.
